### ISSUE TITLE
Please provide OSX install instructions

### ISSUE THREAD

**Issue by ghost** [wilecoyote2015/VerySharp#1]
Not being too familiar with Python I tried to run VerySharp on OSX and failed miserably. I won't even try to document my unsuccessful attempts to avoid embarrassment.

Please provide install instructions for OSX.

**Comment by wilecoyote2015** [comment]
Hi Gilead!
I have added some instructions on how to set up Python accordingly.
Unfortunately, installing OpenCV is a bit complicated for mac. I hope that it will become easier in the future.
